-- CREATE TABLE doctor (
--     doctorId INT AUTO_INCREMENT PRIMARY KEY,
--     doctorName VARCHAR(100) NOT NULL,
--     address VARCHAR(255),
--     doctorDepartment VARCHAR(100) NOT NULL,
--     phone VARCHAR(20),
--     emailId VARCHAR(100) UNIQUE NOT NULL,
--     doctorPassword VARCHAR(50),
--     doctorConfirmPassword VARCHAR(50)
-- );
select * from doctor;